import tailwindcss from '@tailwindcss/vite'
import { minimal2023Preset } from '@vite-pwa/assets-generator/config'

const siteUrl = 'https://password.dwinkelmann.com/'
const siteTitle = 'Password Generator – Strong & Apple-Style Passwords'
const siteDescription = 'Generate strong, random passwords right in your browser – including Apple-style passwords like meXhy8-pidtad-pobgeh. Free, works offline, nothing leaves your device.'

// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },
  ssr: false,

  modules: [
    '@nuxtjs/i18n',
    '@vueuse/nuxt',
    '@vite-pwa/nuxt',
    '@nuxt/icon',
  ],

  icon: {
    // Inline SVGs so icon paths can be animated; bundle them so the PWA works offline
    mode: 'svg',
    clientBundle: {
      scan: true,
    },
  },

  css: ['~/assets/css/tailwind.css'],

  vite: {
    plugins: [tailwindcss()],
  },

  pwa: {
    registerType: 'autoUpdate',
    // Capture beforeinstallprompt so InstallButton can trigger the native install dialog
    client: {
      installPrompt: true,
    },
    manifest: {
      name: 'The Password App',
      short_name: 'Password Generator',
      description: siteDescription,
      categories: ['security', 'utilities'],
      theme_color: '#040F2D',
      background_color: '#040F2D',
      display: 'standalone',
      lang: 'en',
    },
    pwaAssets: {
      image: 'public/pwa-icon.svg',
      // The source already has its own background and padding, so don't add the preset's white border
      preset: {
        ...minimal2023Preset,
        maskable: { ...minimal2023Preset.maskable, padding: 0, resizeOptions: { background: '#040F2D' } },
        apple: { ...minimal2023Preset.apple, padding: 0, resizeOptions: { background: '#040F2D' } },
      },
    },
    workbox: {
      navigateFallback: '/',
      globPatterns: ['**/*.{js,css,html,png,svg,ico}'],
      globIgnores: ['og-image.png'],
    },
  },

  // Emit the SPA shell as static index.html so the service worker can serve it offline
  nitro: {
    prerender: {
      routes: ['/'],
    },
  },

  // Everything SEO-relevant is static here: with ssr: false, crawlers and link previews only see the
  // prerendered shell. app.vue swaps title and description for the active language at runtime.
  app: {
    head: {
      htmlAttrs: { lang: 'en' },
      title: siteTitle,
      // cover lets the dark background run under the notch and home indicator
      viewport: 'width=device-width, initial-scale=1, viewport-fit=cover',
      meta: [
        { name: 'description', content: siteDescription },
        { name: 'author', content: 'Daniel Winkelmann' },
        { property: 'og:type', content: 'website' },
        { property: 'og:site_name', content: 'Password Generator' },
        { property: 'og:url', content: siteUrl },
        { property: 'og:title', content: siteTitle },
        { property: 'og:description', content: siteDescription },
        { property: 'og:image', content: `${siteUrl}og-image.png` },
        { property: 'og:image:width', content: '1200' },
        { property: 'og:image:height', content: '630' },
        { property: 'og:image:alt', content: 'Password Generator showing an Apple-style password' },
        { property: 'og:locale', content: 'en_US' },
        { name: 'twitter:card', content: 'summary_large_image' },
        { name: 'twitter:title', content: siteTitle },
        { name: 'twitter:description', content: siteDescription },
        { name: 'twitter:image', content: `${siteUrl}og-image.png` },
        { name: 'theme-color', content: '#040F2D' },
        { name: 'mobile-web-app-capable', content: 'yes' },
        { name: 'apple-mobile-web-app-capable', content: 'yes' },
        { name: 'apple-mobile-web-app-status-bar-style', content: 'black-translucent' },
        { name: 'apple-mobile-web-app-title', content: 'Password Generator' },
      ],
      // Static so they're in the prerendered HTML (ssr: false would only add them at runtime);
      // files are generated by pwaAssets from public/pwa-icon.svg
      link: [
        { rel: 'icon', href: '/favicon.ico', sizes: '48x48' },
        { rel: 'icon', href: '/pwa-icon.svg', sizes: 'any', type: 'image/svg+xml' },
        { rel: 'apple-touch-icon', href: '/apple-touch-icon-180x180.png' },
        { rel: 'manifest', href: '/manifest.webmanifest' },
        { rel: 'canonical', href: siteUrl },
      ],
      script: [
        {
          type: 'application/ld+json',
          textContent: JSON.stringify({
            '@context': 'https://schema.org',
            '@type': 'WebApplication',
            'name': 'Password Generator',
            'url': siteUrl,
            'description': siteDescription,
            'image': `${siteUrl}og-image.png`,
            'applicationCategory': 'SecurityApplication',
            'operatingSystem': 'Any',
            'browserRequirements': 'Requires JavaScript',
            'inLanguage': ['en', 'de', 'fr', 'es', 'pl'],
            'offers': { '@type': 'Offer', 'price': '0', 'priceCurrency': 'EUR' },
            'author': { '@type': 'Person', 'name': 'Daniel Winkelmann' },
          }),
        },
      ],
      noscript: [
        { textContent: `${siteTitle}. ${siteDescription} Please enable JavaScript to use it.`, tagPosition: 'bodyOpen' },
      ],
    },
  },

  i18n: {
    locales: [
      {
        code: 'en',
        language: 'en-US',
        file: 'en.yml',
        name: 'English',
      },
      {
        code: 'de',
        language: 'de-DE',
        file: 'de.yml',
        name: 'Deutsch',
      },
      {
        code: 'fr',
        language: 'fr-FR',
        file: 'fr.yml',
        name: 'Français',
      },
      {
        code: 'es',
        language: 'es-ES',
        file: 'es.yml',
        name: 'Español',
      },
      {
        code: 'pl',
        language: 'pl-PL',
        file: 'pl.yml',
        name: 'Polski',
      },
    ],
    strategy: 'no_prefix',
    defaultLocale: 'en',
    detectBrowserLanguage: {
      useCookie: true,
    },
  },

  compatibilityDate: '2026-10-07',
})
