// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./components/Footer.vue')['default']
    GenerateButton: typeof import('./components/GenerateButton.vue')['default']
    PasswordTile: typeof import('./components/PasswordTile.vue')['default']
    PasswordTileCharacter: typeof import('./components/PasswordTileCharacter.vue')['default']
    README: typeof import('./components/README.md')['default']
    SliderTile: typeof import('./components/SliderTile.vue')['default']
    Toggle: typeof import('./components/Toggle.vue')['default']
    ToggleTile: typeof import('./components/ToggleTile.vue')['default']
  }
}

export { }
